export { default as callToAction } from "./callToAction";
export { default as header } from "./header";
export { default as footer } from "./footer";
export { default as socialMenuWidget } from "./socialMenuWidget";
export { default as footerWidgetMenu } from "./footerWidgetMenu";
export { default as descriptionWidget } from "./descriptionWidget";
export { default as navigationMenu } from "./navigationMenu";
export { default as home_landing_section } from "./homeLandingSection";
export { default as LeftTitleRightDesc } from "./LeftTitleRightDesc";
export { default as CounterSection } from "./CounterSection";
export { default as userCounter } from "./userCounter";
export { default as serviceTypeInputs } from "./serviceTypeInputs";
export { default as serviceTypeSection } from "./serviceTypeSection";
// export { default as twoCardTestimonialsInput } from "./twoCardTestimonialsInput";
// export { default as twoCardTestimonials } from "./twoCardTestimonials";
export { default as testimonials } from "./testimonials";
export { default as testimonialsInputs } from "./testimonialsInputs"
export { default as TextWithCardSection } from "./TextWithCardSection";
export { default as homeTextWithCard } from "./homeTextWithCard";
export { default as BestRewardSection } from "./BestRewardSection";
export { default as OurTeamSection } from "./OurTeamSection";
export { default as ourTeamProfile } from "./ourTeamProfile";
export { default as FinacialToolSection } from "./FinacialToolSection";
export { default as homeFinancialTool } from "./homeFinancialTool";
export { default as OurPartnerSection } from "./OurPartnerSection";
export { default as ourPartner } from "./ourPartner";
